### ISSUE TITLE
Indexar las oferta en el README

### ISSUE THREAD

**Issue by gonzaloserrano** [getmanfred/offers#1]
Me ha costado un poco llegar a ver las páginas de la wiki, si tenéis las ofertas abiertas indexadas en el README se verá nada más entrar, e incluso la peña podría actualizarse el listado haciendo un `git pull`.

**Comment by GorkaPuente** [comment]
Hola Gonzalo
Puedes clonarte la wiki si quieres y hacer pull para ver nuevas ofertas, utiliza

https://github.com/getmanfred/offers.wiki.git

Saludos,
Gorka

**Comment by gonzaloserrano** [comment]
Anda, no tenía idea de que la wiki estaba indexada en git. Gracias!
