### ISSUE TITLE
How to get in contact ?

### ISSUE THREAD

**Issue by drochag** [getmanfred/offers#3]
En las posiciones listadas, por ejemplo [esta](https://github.com/getmanfred/offers/wiki/Frontend-Developer-para-ICTI-(Remoto-100%25)-entre-%E2%82%AC28-%E2%9E%96-30K-fijo-%E2%9E%95-Variable), menciona que si somos parte de manfred sólo nos contactemos con uds, pero no se a qué se refiera esto, hace mucho que estoy en el grupo de Telegram, pero eso es todo (y evidentemente no se puede mandar mensaje)

**Comment by fjcoira** [comment]
Hola DanMMX. Se refiere a si en alguna ocasión te has registrado como manfredita ( [enlace al formulario](https://getmanfred.typeform.com/to/GDvgX5) ), nos avises, por ejemplo, respondiendo al correo del bienvenida que te enviamos.

**Comment by drochag** [comment]
Muchas gracias!
