### ISSUE TITLE
Enlace a oferta no funciona

### ISSUE THREAD

**Issue by eckelon** [getmanfred/offers#4]
Hola!

Este enlace lleva a la Wiki en vez de al detalle de la oferta:

Project Manager (Entre €33 y 38K) para Comunitelia en Tomelloso con Remoto Parcial - https://github.com/getmanfred/offers/wiki/Project-Manager-(Entre-€33-y-38K)-para-Comunitelia-en-Tomelloso-con-Remoto-Parcial

Gracias!!

**Comment by fjcoira** [comment]
Corregido, ¡gracias por avisar!.

Y por si acaso, dejo aquí el enlace: [a la oferta](https://bit.ly/3eoQiCd)

**Comment by fjcoira** [comment]
Fixed
