### ISSUE TITLE
Typo in este sencillo formulario

### ISSUE THREAD

**Issue by DanielCalvo** [getmanfred/offers#5]
Hey friends at Manfred!

After clicking submit in the typeform page here: https://getmanfred.typeform.com/to/GDvgX5 It is written "Thank your for your submit" which is incorrect. The correct English would be "Thank you for your submission".

**Comment by JuanVentrone** [comment]
Is not an Issue, just pass here and say that I sent my Resume to jose@getmanfred.com so have fun!
